In [40]:
# Import requirements
import pandas as pd
from get_all_traces import *
import matplotlib.pyplot as plt

In [41]:
# Load in catalog with date_time for pulling IRIS waveforms
sample_catalog = pd.read_csv('../data/old_catalog_with_geometry_filtered.csv')

In [42]:
sample_catalog = sample_catalog.head(100)

In [43]:
#sample_catalog.to_csv('../data/old_catalog_with_geometry_filtered_mini.csv', index=False)

In [44]:
display(sample_catalog)

,event_id,event_datetime,event_lat,event_lon,event_depth,arrival_time,weight,phase_type,quality,line_number_phase,...,raw_line_event,magnitude,datetime,station_id,station_lat,station_lon,station_elev,back_azimuth,epicentral_distance_km,angle_of_incidence
0,0.033,2015-01-22T00:00:27.537Z,45.94689,-129.99863,0.547,0.424,1.00,P,NaN,2,...,# 2015 1 22 0 0 27.537 45.94689 -129.9986...,-0.3,2015-01-22 00:00:27.537,AXCC1,45.955,-130.008,-1.516,141.221916,1.156714,29.279135
1,0.033,2015-01-22T00:00:27.537Z,45.94689,-129.99863,0.547,1.209,0.25,S,NaN,5,...,# 2015 1 22 0 0 27.537 45.94689 -129.9986...,-0.3,2015-01-22 00:00:27.537,AXCC1,45.955,-130.008,-1.516,141.221916,1.156714,29.279135
2,0.030,2015-01-22T02:02:41.042Z,45.94109,-130.01480,0.675,0.583,0.25,P,NaN,28,...,# 2015 1 22 2 2 41.042 45.94109 -130.0148...,-0.0,2015-01-22 02:02:41.042,AXAS1,45.936,-130.013,-1.516,346.184201,0.582846,14.896736
3,0.030,2015-01-22T02:02:41.042Z,45.94109,-130.01480,0.675,0.358,1.00,P,NaN,29,...,# 2015 1 22 2 2 41.042 45.94109 -130.0148...,-0.0,2015-01-22 02:02:41.042,AXAS2,45.936,-130.013,-1.516,346.184201,0.582846,14.896736
4,0.030,2015-01-22T02:02:41.042Z,45.94109,-130.01480,0.675,1.178,0.12,S,NaN,34,...,# 2015 1 22 2 2 41.042 45.94109 -130.0148...,-0.0,2015-01-22 02:02:41.042,AXAS1,45.936,-130.013,-1.516,346.184201,0.582846,14.896736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.071,2015-01-22T05:45:28.595Z,45.93651,-130.02013,1.358,0.595,0.75,P,NaN,333,...,# 2015 1 22 5 45 28.595 45.93651 -130.0201...,0.1,2015-01-22 05:45:28.595,AXAS1,45.936,-130.013,-1.516,275.874856,0.554282,10.916081
96,0.071,2015-01-22T05:45:28.595Z,45.93651,-130.02013,1.358,0.395,1.00,P,NaN,334,...,# 2015 1 22 5 45 28.595 45.93651 -130.0201...,0.1,2015-01-22 05:45:28.595,AXAS2,45.936,-130.013,-1.516,275.874856,0.554282,10.916081
97,0.071,2015-01-22T05:45:28.595Z,45.93651,-130.02013,1.358,1.290,0.25,S,NaN,339,...,# 2015 1 22 5 45 28.595 45.93651 -130.0201...,0.1,2015-01-22 05:45:28.595,AXAS1,45.936,-130.013,-1.516,275.874856,0.554282,10.916081
98,0.071,2015-01-22T05:45:28.595Z,45.93651,-130.02013,1.358,0.605,0.17,S,NaN,340,...,# 2015 1 22 5 45 28.595 45.93651 -130.0201...,0.1,2015-01-22 05:45:28.595,AXAS2,45.936,-130.013,-1.516,275.874856,0.554282,10.916081
99,0.043,2015-01-22T05:49:22.217Z,45.94630,-129.98380,1.699,0.468,0.75,P,NaN,343,...,# 2015 1 22 5 49 22.217 45.94630 -129.9838...,-0.1,2015-01-22 05:49:22.217,AXEC1,45.955,-129.973,-1.519,220.801468,1.277896,21.658455

In [45]:
# Convert datetime column to datetime type if it's a string
sample_catalog['datetime'] = pd.to_datetime(sample_catalog['datetime'])
# Add 15 seconds to datetime to create endtime
sample_catalog['endtime'] = sample_catalog['datetime'] + pd.Timedelta(seconds=15)

In [46]:
sample_catalog = sample_catalog.drop(['month', 'day', 'hour','minute', 'second', 'event_datetime', 'weight', 
                                      'datetime_str', 'event_lat', 'event_lon', 'event_depth', 'quality',
                                      'line_number_phase'], axis=1)

In [47]:
sample_catalog = sample_catalog.drop(['line_number_event', 'raw_line_event'], axis=1)

In [48]:
sample_catalog = sample_catalog.drop(['raw_line_phase'], axis=1)

In [49]:
display(sample_catalog)

,event_id,arrival_time,phase_type,year,lat,lon,depth,magnitude,datetime,station_id,station_lat,station_lon,station_elev,back_azimuth,epicentral_distance_km,angle_of_incidence,endtime
0,0.033,0.424,P,2015,45.94689,-129.99863,0.547,-0.3,2015-01-22 00:00:27.537,AXCC1,45.955,-130.008,-1.516,141.221916,1.156714,29.279135,2015-01-22 00:00:42.537
1,0.033,1.209,S,2015,45.94689,-129.99863,0.547,-0.3,2015-01-22 00:00:27.537,AXCC1,45.955,-130.008,-1.516,141.221916,1.156714,29.279135,2015-01-22 00:00:42.537
2,0.030,0.583,P,2015,45.94109,-130.01480,0.675,-0.0,2015-01-22 02:02:41.042,AXAS1,45.936,-130.013,-1.516,346.184201,0.582846,14.896736,2015-01-22 02:02:56.042
3,0.030,0.358,P,2015,45.94109,-130.01480,0.675,-0.0,2015-01-22 02:02:41.042,AXAS2,45.936,-130.013,-1.516,346.184201,0.582846,14.896736,2015-01-22 02:02:56.042
4,0.030,1.178,S,2015,45.94109,-130.01480,0.675,-0.0,2015-01-22 02:02:41.042,AXAS1,45.936,-130.013,-1.516,346.184201,0.582846,14.896736,2015-01-22 02:02:56.042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.071,0.595,P,2015,45.93651,-130.02013,1.358,0.1,2015-01-22 05:45:28.595,AXAS1,45.936,-130.013,-1.516,275.874856,0.554282,10.916081,2015-01-22 05:45:43.595
96,0.071,0.395,P,2015,45.93651,-130.02013,1.358,0.1,2015-01-22 05:45:28.595,AXAS2,45.936,-130.013,-1.516,275.874856,0.554282,10.916081,2015-01-22 05:45:43.595
97,0.071,1.290,S,2015,45.93651,-130.02013,1.358,0.1,2015-01-22 05:45:28.595,AXAS1,45.936,-130.013,-1.516,275.874856,0.554282,10.916081,2015-01-22 05:45:43.595
98,0.071,0.605,S,2015,45.93651,-130.02013,1.358,0.1,2015-01-22 05:45:28.595,AXAS2,45.936,-130.013,-1.516,275.874856,0.554282,10.916081,2015-01-22 05:45:43.595
99,0.043,0.468,P,2015,45.94630,-129.98380,1.699,-0.1,2015-01-22 05:49:22.217,AXEC1,45.955,-129.973,-1.519,220.801468,1.277896,21.658455,2015-01-22 05:49:37.217

In [50]:
catalog = sample_catalog

In [51]:
# For each event, with phase_type 'P', save arrival_time as 'p_arrival_time' and with phase_type 'S', save arrival_time as 's_arrival_time'
p_arrivals = catalog[catalog['phase_type'] == 'P'][['event_id', 'arrival_time']].rename(columns={'arrival_time': 'p_arrival_time'})
s_arrivals = catalog[catalog['phase_type'] == 'S'][['event_id', 'arrival_time']].rename(columns={'arrival_time': 's_arrival_time'})

# Merge P and S arrivals back into the main catalog
catalog = catalog.merge(p_arrivals, on='event_id', how='left').merge(s_arrivals, on='event_id', how='left')

# Remove duplicates based on id and station_id, keeping the first occurrence
catalog_final = catalog.drop_duplicates(subset=['event_id', 'station_id'])

In [52]:
catalog_final = catalog_final.drop(['phase_type', 'arrival_time'], axis=1)

In [53]:
display(catalog_final)

,event_id,year,lat,lon,depth,magnitude,datetime,station_id,station_lat,station_lon,station_elev,back_azimuth,epicentral_distance_km,angle_of_incidence,endtime,p_arrival_time,s_arrival_time
0,0.033,2015,45.94689,-129.99863,0.547,-0.3,2015-01-22 00:00:27.537,AXCC1,45.955,-130.008,-1.516,141.221916,1.156714,29.279135,2015-01-22 00:00:42.537,0.424,1.209
98,0.030,2015,45.94109,-130.01480,0.675,-0.0,2015-01-22 02:02:41.042,AXAS1,45.936,-130.013,-1.516,346.184201,0.582846,14.896736,2015-01-22 02:02:56.042,0.583,1.178
102,0.030,2015,45.94109,-130.01480,0.675,-0.0,2015-01-22 02:02:41.042,AXAS2,45.936,-130.013,-1.516,346.184201,0.582846,14.896736,2015-01-22 02:02:56.042,0.583,1.178
114,0.079,2015,45.94880,-129.99129,1.562,0.1,2015-01-22 02:39:20.658,AXCC1,45.955,-130.008,-1.516,118.081166,1.464290,25.441723,2015-01-22 02:39:35.658,0.522,1.222
150,0.079,2015,45.94880,-129.99129,1.562,0.1,2015-01-22 02:39:20.658,AXEC1,45.955,-129.973,-1.519,244.014489,1.573105,27.048067,2015-01-22 02:39:35.658,0.522,1.222
186,0.079,2015,45.94880,-129.99129,1.562,0.1,2015-01-22 02:39:20.658,AXEC2,45.955,-129.973,-1.519,244.014489,1.573105,27.048067,2015-01-22 02:39:35.658,0.522,1.222
222,0.079,2015,45.94880,-129.99129,1.562,0.1,2015-01-22 02:39:20.658,AXEC3,45.955,-129.973,-1.519,244.014489,1.573105,27.048067,2015-01-22 02:39:35.658,0.522,1.222
258,0.079,2015,45.94287,-130.02107,0.519,-0.2,2015-01-22 16:02:30.935,AXAS1,45.936,-130.013,-1.516,320.757897,0.986392,25.860095,2015-01-22 16:02:45.935,0.522,1.222
294,0.079,2015,45.94287,-130.02107,0.519,-0.2,2015-01-22 16:02:30.935,AXAS2,45.936,-130.013,-1.516,320.757897,0.986392,25.860095,2015-01-22 16:02:45.935,0.522,1.222
546,0.072,2015,45.94606,-129.98662,1.305,0.3,2015-01-22 02:59:40.845,AXEC1,45.955,-129.973,-1.519,226.653013,1.448093,27.147880,2015-01-22 02:59:55.845,0.425,0.810
555,0.072,2015,45.94606,-129.98662,1.305,0.3,2015-01-22 02:59:40.845,AXEC2,45.955,-129.973,-1.519,226.653013,1.448093,27.147880,2015-01-22 02:59:55.845,0.425,0.810
564,0.072,2015,45.94606,-129.98662,1.305,0.3,2015-01-22 02:59:40.845,AXEC3,45.955,-129.973,-1.519,226.653013,1.448093,27.147880,2015-01-22 02:59:55.845,0.425,0.810
600,0.152,2015,45.93476,-130.01872,1.226,0.4,2015-01-22 03:00:46.773,AXAS1,45.936,-130.013,-1.516,252.689389,0.463334,9.591051,2015-01-22 03:01:01.773,0.502,1.242
609,0.152,2015,45.93476,-130.01872,1.226,0.4,2015-01-22 03:00:46.773,AXAS2,45.936,-130.013,-1.516,252.689389,0.463334,9.591051,2015-01-22 03:01:01.773,0.502,1.242
618,0.152,2015,45.93476,-130.01872,1.226,0.4,2015-01-22 03:00:46.773,AXID1,45.934,-130.004,-1.512,274.250963,1.141490,22.631566,2015-01-22 03:01:01.773,0.502,1.242
654,0.087,2015,45.95464,-129.99290,1.117,0.3,2015-01-22 03:01:31.650,AXCC1,45.955,-130.008,-1.516,91.958623,1.168000,23.922091,2015-01-22 03:01:46.650,0.455,1.130
656,0.070,2015,45.93618,-130.01025,0.770,-0.2,2015-01-22 03:21:07.809,AXAS1,45.936,-130.013,-1.516,84.622351,0.213602,5.338169,2015-01-22 03:21:22.809,0.391,0.951
662,0.070,2015,45.93618,-130.01025,0.770,-0.2,2015-01-22 03:21:07.809,AXAS2,45.936,-130.013,-1.516,84.622351,0.213602,5.338169,2015-01-22 03:21:22.809,0.391,0.951
668,0.070,2015,45.93618,-130.01025,0.770,-0.2,2015-01-22 03:21:07.809,AXID1,45.934,-130.004,-1.512,296.637351,0.540712,13.330199,2015-01-22 03:21:22.809,0.391,0.951
686,0.034,2015,45.94294,-130.01294,0.617,0.1,2015-01-22 03:37:40.683,AXAS1,45.936,-130.013,-1.516,0.344451,0.771707,19.889823,2015-01-22 03:37:55.683,0.747,1.342
695,0.034,2015,45.94294,-130.01294,0.617,0.1,2015-01-22 03:37:40.683,AXAS2,45.936,-130.013,-1.516,0.344451,0.771707,19.889823,2015-01-22 03:37:55.683,0.747,1.342
704,0.034,2015,45.94294,-130.01294,0.617,0.1,2015-01-22 03:37:40.683,AXID1,45.934,-130.004,-1.512,325.187284,1.210833,29.628333,2015-01-22 03:37:55.683,0.747,1.342
740,0.037,2015,45.95569,-129.98146,2.477,0.6,2015-01-22 03:40:37.451,AXCC1,45.955,-130.008,-1.516,87.848819,2.053104,27.211126,2015-01-22 03:40:52.451,0.884,1.144
756,0.037,2015,45.95569,-129.98146,2.477,0.6,2015-01-22 03:40:37.451,AXEC1,45.955,-129.973,-1.519,276.694167,0.658484,9.357433,2015-01-22 03:40:52.451,0.884,1.144
772,0.037,2015,45.95569,-129.98146,2.477,0.6,2015-01-22 03:40:37.451,AXEC2,45.955,-129.973,-1.519,276.694167,0.658484,9.357433,2015-01-22 03:40:52.451,0.884,1.144
788,0.037,2015,45.95569,-129.98146,2.477,0.6,2015-01-22 03:40:37.451,AXEC3,45.955,-129.973,-1.519,276.694167,0.658484,9.357433,2015-01-22 03:40:52.451,0.884,1.144
868,0.017,2015,45.96289,-129.99789,2.127,0.1,2015-01-22 03:43:42.368,AXCC1,45.955,-130.008,-1.516,41.690179,1.174925,17.875325,2015-01-22 03:43:57.368,0.597,1.327
870,0.046,2015,45.95920,-130.00198,1.469,0.4,2015-01-22 03:43:52.087,AXCC1,45.955,-130.008,-1.516,44.895919,0.659292,12.454874,2015-01-22 03:44:07.087,0.433,1.248
879,0.046,2015,45.94185,-130.02161,1.384,0.8,2015-01-22 10:34:31.020,AXAS2,45.936,-130.013,-1.516,314.337084,0.930815,17.795103,2015-01-22 10:34:46.020,0.433,1.248
888,0.046,2015,45.94185,-130.02161,1.384,0.8,2015-01-22 10:34:31.020,AXID1,45.934,-130.004,-1.512,302.665856,1.617506,29.184712,2015-01-22 10:34:46.020,0.433,1.248
906,0.046,2015,45.94185,-130.02161,1.384,0.8,2015-01-22 10:34:31.020,AXAS1,45.936,-130.013,-1.516,314.337084,0.930815,17.795103,2015-01-22 10:34:46.020,0.433,1.248
973,0.033,2015,45.93935,-130.01962,0.818,0.3,2015-01-22 04:45:04.026,AXAS1,45.936,-130.013,-1.516,306.044160,0.633105,15.176472,2015-01-22 04:45:19.026,0.424,1.209
1071,0.033,2015,45.93935,-130.01962,0.818,0.3,2015-01-22 04:45:04.026,AXAS2,45.936,-130.013,-1.516,306.044160,0.633105,15.176472,2015-01-22 04:45:19.026,0.424,1.209
1169,0.033,2015,45.93964,-130.01918,1.162,0.1,2015-01-22 23:13:29.580,AXID1,45.934,-130.004,-1.512,298.118605,1.330900,26.460400,2015-01-22 23:13:44.580,0.424,1.209
1512,0.082,2015,45.95070,-129.99330,0.863,-0.1,2015-01-22 04:49:52.325,AXCC1,45.955,-130.008,-1.516,112.812978,1.232921,27.395523,2015-01-22 04:50:07.325,0.450,1.265
1514,0.067,2015,45.93511,-129.99628,0.000,-0.2,2015-01-22 04:51:47.759,AXID1,45.934,-130.004,-1.512,78.316543,0.609642,21.959407,2015-01-22 04:52:02.759,1.291,NaN
1515,0.062,2015,45.93621,-130.01622,1.209,-0.1,2015-01-22 04:56:42.730,AXAS1,45.936,-130.013,-1.516,275.358452,0.250100,5.243912,2015-01-22 04:56:57.730,0.555,1.210
1641,0.062,2015,45.93621,-130.01622,1.209,-0.1,2015-01-22 04:56:42.730,AXAS2,45.936,-130.013,-1.516,275.358452,0.250100,5.243912,2015-01-22 04:56:57.730,0.555,1.210
1767,0.062,2015,45.93621,-130.01622,1.209,-0.1,2015-01-22 04:56:42.730,AXID1,45.934,-130.004,-1.512,284.580780,0.976438,19.740664,2015-01-22 04:56:57.730,0.555,1.210
2061,0.069,2015,45.95247,-129.99567,0.518,0.0,2015-01-22 05:01:53.744,AXCC1,45.955,-130.008,-1.516,106.438837,0.993844,26.040845,2015-01-22 05:02:08.744,0.396,1.091
2063,0.015,2015,45.94548,-129.98318,1.174,-0.2,2015-01-22 05:37:03.623,AXEC1,45.955,-129.973,-1.519,216.633916,1.319093,26.096675,2015-01-22 05:37:18.623,0.372,0.792
2072,0.015,2015,45.94548,-129.98318,1.174,-0.2,2015-01-22 05:37:03.623,AXEC2,45.955,-129.973,-1.519,216.633916,1.319093,26.096675,2015-01-22 05:37:18.623,0.372,0.792
2081,0.015,2015,45.94548,-129.98318,1.174,-0.2,2015-01-22 05:37:03.623,AXEC3,45.955,-129.973,-1.519,216.633916,1.319093,26.096675,2015-01-22 05:37:18.623,0.372,0.792
2117,0.071,2015,45.93651,-130.02013,1.358,0.1,2015-01-22 05:45:28.595,AXAS1,45.936,-130.013,-1.516,275.874856,0.554282,10.916081,2015-01-22 05:45:43.595,0.595,1.290
2121,0.071,2015,45.93651,-130.02013,1.358,0.1,2015-01-22 05:45:28.595,AXAS2,45.936,-130.013,-1.516,275.874856,0.554282,10.916081,2015-01-22 05:45:43.595,0.595,1.290
2133,0.043,2015,45.94630,-129.98380,1.699,-0.1,2015-01-22 05:49:22.217,AXEC1,45.955,-129.973,-1.519,220.801468,1.277896,21.658455,2015-01-22 05:49:37.217,0.468,NaN

In [54]:
get_all_traces(catalog_final, 'old_catalog_waveforms_100', 'datetime', 'endtime')

Retrieved data for AXCC1 HHE from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXCC1 HHN from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXCC1 HHZ from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXCC1 HDH from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC1 EHE from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC1 EHN from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC1 EHZ from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC2 HHE from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC2 HHN from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC2 HHZ from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC2 HDH from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC3 EHE from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC3 EHN from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXEC3 EHZ from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXAS1 EHE from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXAS1 EHN from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXAS1 EHZ from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXAS2 EHE from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXAS2 EHN from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXAS2 EHZ from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXID1 EHE from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXID1 EHN from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXID1 EHZ from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXBA1 HHE from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXBA1 HHN from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXBA1 HHZ from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXBA1 HDH from 2015-01-22T00:00:27.537000Z to 2015-01-22T00:00:42.537000Z
Retrieved data for AXCC1 HHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXCC1 HHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXCC1 HHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXCC1 HDH from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC1 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC1 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC1 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC2 HHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC2 HHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC2 HHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC2 HDH from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC3 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC3 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC3 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS1 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS1 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS1 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS2 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS2 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS2 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXID1 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXID1 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXID1 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXBA1 HHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXBA1 HHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXBA1 HHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXBA1 HDH from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXCC1 HHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXCC1 HHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXCC1 HHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXCC1 HDH from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC1 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC1 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC1 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC2 HHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC2 HHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC2 HHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC2 HDH from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC3 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC3 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXEC3 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS1 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS1 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS1 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS2 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS2 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXAS2 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXID1 EHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXID1 EHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXID1 EHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXBA1 HHE from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXBA1 HHN from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXBA1 HHZ from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXBA1 HDH from 2015-01-22T02:02:41.042000Z to 2015-01-22T02:02:56.042000Z
Retrieved data for AXCC1 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC2 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXEC3 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXAS2 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXID1 EHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHE from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHN from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HHZ from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXBA1 HDH from 2015-01-22T02:39:20.658000Z to 2015-01-22T02:39:35.658000Z
Retrieved data for AXCC1 HHE from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXCC1 HHN from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXCC1 HHZ from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXCC1 HDH from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC1 EHE from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC1 EHN from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC1 EHZ from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC2 HHE from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC2 HHN from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC2 HHZ from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC2 HDH from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC3 EHE from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC3 EHN from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXEC3 EHZ from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXAS1 EHE from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXAS1 EHN from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXAS1 EHZ from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXAS2 EHE from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXAS2 EHN from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXAS2 EHZ from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXID1 EHE from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXID1 EHN from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXID1 EHZ from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXBA1 HHE from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXBA1 HHN from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z
Retrieved data for AXBA1 HHZ from 2015-01-22T16:02:30.935000Z to 2015-01-22T16:02:45.935000Z

1242 Trace(s) in Stream:

OO.AXCC1..HHE | 2015-01-22T00:00:27.540000Z - 2015-01-22T00:00:42.535000Z | 200.0 Hz, 3000 samples
...
(1240 other traces)
...
OO.AXBA1..HDH | 2015-01-22T05:49:22.220000Z - 2015-01-22T05:49:37.215000Z | 200.0 Hz, 3000 samples

[Use "print(Stream.__str__(extended=True))" to print all Traces]

In [55]:
catalog_final.to_csv('../data/old_catalog_with_geometry_filtered_100.csv', index=False)